# cloudbuild.yaml (frontend)
substitutions:
  _SERVICE_NAME: "maumii"        # Cloud Run 프론트 서비스 이름
  _REGION: "us-central1"

steps:
  # 1) 프론트 빌드
  - name: node:20
    entrypoint: bash
    args:
      - -c
      - |
        npm ci
        npm run build

  # 2) 컨테이너 이미지 빌드 (Nginx로 정적파일 서빙)
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA', '.']

  # 3) 푸시
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA']

  # 4) Cloud Run 배포
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        'run','deploy','${_SERVICE_NAME}',
        '--image','gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
        '--region','${_REGION}',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'